# Generated by Django 5.1.15 on 2026-10-05 12:41

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Production API Key', max_length=100, verbose_name='Key Name')),
                ('prefix', models.CharField(db_index=True, max_length=12, verbose_name='Key Prefix')),
                ('hashed_key', models.CharField(max_length=128, verbose_name='Hashed Secret')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('ip_whitelist', models.JSONField(blank=True, default=list, verbose_name='IP Whitelist')),
                ('rate_limit_rpm', models.PositiveIntegerField(blank=True, help_text='Custom requests per minute limit, configurable by admin per client', null=True, verbose_name='Custom Rate Limit (RPM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Callback URL')),
                ('secret', models.CharField(default=secrets.token_hex, max_length=128, verbose_name='HMAC Signing Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_webhook', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Webhook Config',
                'verbose_name_plural': 'Client Webhook Configs',
            },
        ),
        migrations.CreateModel(
            name='WebhookForwardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=50, verbose_name='Message ID')),
                ('url', models.URLField(max_length=500, verbose_name='Destination URL')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload Forwarded')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP Response Code')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='Response Body')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Success')),
                ('attempt', models.PositiveIntegerField(default=1, verbose_name='Attempt Number')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_forward_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Forward Log',
                'verbose_name_plural': 'Webhook Forward Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
