"""Utilities for exporting onboarding applications to ZIP and Excel for operators."""
import io
import json
import zipfile
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from django.core.files.storage import default_storage


def generate_application_text_summary(app):
    """Generate a clean, professional text summary for carrier forwarding."""
    return f"""========================================================================
RCS BUSINESS MESSAGING (RBM) - BOT ONBOARDING APPLICATION
========================================================================
Application ID: #{app.id}
Submission Date: {app.created_at.strftime('%Y-%m-%d %H:%M:%S')}
Status: {app.get_status_display()}
Submitting Account: {app.user.get_full_name()} (@{app.user.username})
Company: {app.user.company_name}

------------------------------------------------------------------------
1. MESSAGE PROFILE
------------------------------------------------------------------------
Bot Message Type: {app.bot_message_type}

------------------------------------------------------------------------
2. BRAND & BOT IDENTITY
------------------------------------------------------------------------
Brand Name: {app.brand_name}
Bot Name: {app.bot_name}
Brand SPOC Name: {app.brand_spoc_name}
Brand SPOC Designation: {app.brand_spoc_designation}
Brand SPOC Email: {app.brand_spoc_email}
Short Description: {app.short_description}
Primary Brand Colour: {app.color_code}
Languages Supported: {app.languages_supported}

------------------------------------------------------------------------
3. CONTACT INFORMATION
------------------------------------------------------------------------
Primary Phone: {app.primary_phone} (Label: {app.primary_phone_label})
Primary Email: {app.primary_email} (Label: {app.primary_email_label})
Primary Website: {app.primary_website} (Label: {app.primary_website_label})

------------------------------------------------------------------------
4. LEGAL & COMPLIANCE URLS
------------------------------------------------------------------------
Terms & Conditions URL: {app.terms_conditions_url}
Privacy Policy URL: {app.privacy_url}

------------------------------------------------------------------------
5. ATTACHED ASSETS INCLUDED IN DOSSIER
------------------------------------------------------------------------
- Bot Logo: {app.bot_logo.name if app.bot_logo else 'N/A'} (224x224 px)
- Banner Image: {app.banner_image.name if app.banner_image else 'N/A'} (1440x448 px)
- Opt-in Verification Screenshot: {app.opt_in_screenshot.name if app.opt_in_screenshot else 'N/A'}
- GST Certificate: {app.gst_certificate.name if app.gst_certificate else 'N/A'}
- PAN Card: {app.pan_card.name if app.pan_card else 'N/A'}
========================================================================
Generated by RCS Enterprise Portal
"""


def generate_onboarding_zip(app):
    """Build a complete operator onboarding submission ZIP archive with all assets."""
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # 1. Text Summary
        summary_txt = generate_application_text_summary(app)
        zip_file.writestr(f"bot_onboarding_summary_{app.id}.txt", summary_txt.encode("utf-8"))

        # 2. JSON Data
        data_dict = {
            "application_id": app.id,
            "submitted_at": app.created_at.isoformat(),
            "status": app.status,
            "user": {
                "username": app.user.username,
                "email": app.user.email,
                "company": app.user.company_name,
            },
            "bot_message_type": app.get_message_types_list(),
            "bot": {
                "brand_name": app.brand_name,
                "bot_name": app.bot_name,
                "brand_spoc_name": app.brand_spoc_name,
                "brand_spoc_designation": app.brand_spoc_designation,
                "brand_spoc_email": app.brand_spoc_email,
                "short_description": app.short_description,
                "color_code": app.color_code,
                "languages_supported": app.languages_supported,
            },
            "contact": {
                "phone": app.primary_phone,
                "phone_label": app.primary_phone_label,
                "email": app.primary_email,
                "email_label": app.primary_email_label,
                "website": app.primary_website,
                "website_label": app.primary_website_label,
            },
            "legal": {
                "terms_conditions_url": app.terms_conditions_url,
                "privacy_url": app.privacy_url,
            },
            "assets": {
                "bot_logo": app.bot_logo.name if app.bot_logo else None,
                "banner_image": app.banner_image.name if app.banner_image else None,
                "opt_in_screenshot": app.opt_in_screenshot.name if app.opt_in_screenshot else None,
                "gst_certificate": app.gst_certificate.name if app.gst_certificate else None,
                "pan_card": app.pan_card.name if app.pan_card else None,
            },
        }
        zip_file.writestr(f"bot_onboarding_data_{app.id}.json", json.dumps(data_dict, indent=2).encode("utf-8"))

        # 3. Assets: Bot Logo
        if app.bot_logo and default_storage.exists(app.bot_logo.name):
            try:
                with default_storage.open(app.bot_logo.name, "rb") as f:
                    ext = app.bot_logo.name.split(".")[-1]
                    zip_file.writestr(f"assets/bot_logo.{ext}", f.read())
            except Exception:
                pass

        # 4. Assets: Banner Image
        if app.banner_image and default_storage.exists(app.banner_image.name):
            try:
                with default_storage.open(app.banner_image.name, "rb") as f:
                    ext = app.banner_image.name.split(".")[-1]
                    zip_file.writestr(f"assets/banner_image.{ext}", f.read())
            except Exception:
                pass

        # 5. Assets: Opt-in Screenshot
        if app.opt_in_screenshot and default_storage.exists(app.opt_in_screenshot.name):
            try:
                with default_storage.open(app.opt_in_screenshot.name, "rb") as f:
                    ext = app.opt_in_screenshot.name.split(".")[-1]
                    zip_file.writestr(f"assets/opt_in_screenshot.{ext}", f.read())
            except Exception:
                pass

        # 6. Assets: GST Certificate
        if app.gst_certificate and default_storage.exists(app.gst_certificate.name):
            try:
                with default_storage.open(app.gst_certificate.name, "rb") as f:
                    ext = app.gst_certificate.name.split(".")[-1]
                    zip_file.writestr(f"assets/gst_certificate.{ext}", f.read())
            except Exception:
                pass

        # 7. Assets: PAN Card
        if app.pan_card and default_storage.exists(app.pan_card.name):
            try:
                with default_storage.open(app.pan_card.name, "rb") as f:
                    ext = app.pan_card.name.split(".")[-1]
                    zip_file.writestr(f"assets/pan_card.{ext}", f.read())
            except Exception:
                pass

    buffer.seek(0)
    return buffer


def generate_onboarding_excel(queryset):
    """Export one or multiple onboarding applications into an operator spreadsheet."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "RCS Onboarding Applications"

    headers = [
        "App ID",
        "Submission Date",
        "Status",
        "Client Username",
        "Brand Name",
        "Bot Name",
        "Brand SPOC Name",
        "Brand SPOC Designation",
        "Brand SPOC Email",
        "Message Types",
        "Short Description",
        "Colour Code",
        "Phone",
        "Phone Label",
        "Email",
        "Email Label",
        "Website",
        "Website Label",
        "Terms URL",
        "Privacy URL",
        "Languages",
        "GST Certificate File",
        "PAN Card File",
        "Operator Reference ID",
    ]

    header_font = Font(name="Arial", size=11, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="1E40AF", end_color="1E40AF", fill_type="solid")
    center_align = Alignment(horizontal="center", vertical="center")

    for col_num, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_num, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center_align

    for row_idx, app in enumerate(queryset, start=2):
        row_data = [
            app.id,
            app.created_at.strftime("%Y-%m-%d %H:%M"),
            app.get_status_display(),
            app.user.username,
            app.brand_name,
            app.bot_name,
            app.brand_spoc_name,
            app.brand_spoc_designation,
            app.brand_spoc_email,
            app.bot_message_type,
            app.short_description,
            app.color_code,
            app.primary_phone,
            app.primary_phone_label,
            app.primary_email,
            app.primary_email_label,
            app.primary_website,
            app.primary_website_label,
            app.terms_conditions_url,
            app.privacy_url,
            app.languages_supported,
            app.gst_certificate.name if app.gst_certificate else "",
            app.pan_card.name if app.pan_card else "",
            app.operator_reference_id,
        ]
        for col_idx, val in enumerate(row_data, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.alignment = Alignment(vertical="center")

    # Auto-adjust column widths
    for col in ws.columns:
        max_len = max(len(str(cell.value or "")) for cell in col)
        col_letter = openpyxl.utils.get_column_letter(col[0].column)
        ws.column_dimensions[col_letter].width = max(max_len + 3, 12)

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer
