# Generated by Django 5.1.15 on 2026-10-05 11:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_mgmt', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('TRANSACTIONAL', 'Transactional'), ('OTP', 'OTP')], db_index=True, max_length=20, verbose_name='Message Type')),
                ('recipient', models.CharField(max_length=20, verbose_name='Recipient Phone')),
                ('prefix', models.CharField(default='+91', max_length=10, verbose_name='Country Prefix')),
                ('content_type', models.CharField(choices=[('text', 'Plain Text'), ('rich_card', 'Rich Card'), ('carousel', 'Carousel'), ('template', 'Pre-approved Template')], default='text', max_length=20, verbose_name='Content Type')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Custom content payload (text, rich card, or carousel)', verbose_name='Content Payload')),
                ('custom_params', models.JSONField(blank=True, default=dict, help_text='Key-value substitution variables for approved template placeholders', verbose_name='Template Custom Params')),
                ('custref1', models.CharField(blank=True, default='', max_length=100, verbose_name='Custom Ref 1')),
                ('custref2', models.CharField(blank=True, default='', max_length=100, verbose_name='Custom Ref 2')),
                ('custref3', models.CharField(blank=True, default='', max_length=100, verbose_name='Custom Ref 3')),
                ('custref4', models.CharField(blank=True, default='', max_length=100, verbose_name='Custom Ref 4')),
                ('custref5', models.CharField(blank=True, default='', max_length=100, verbose_name='Custom Ref 5')),
                ('custref6', models.CharField(blank=True, default='', max_length=100, verbose_name='Custom Ref 6')),
                ('ttl', models.PositiveIntegerField(blank=True, help_text='TTL duration in seconds', null=True, verbose_name='Time To Live (Seconds)')),
                ('rate_applied', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Frozen unit rate applied at the moment of queuing', max_digits=14, verbose_name='Rate Applied (INR)')),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Frozen total cost debited from wallet', max_digits=14, verbose_name='Total Cost (INR)')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20, verbose_name='Delivery Status')),
                ('onextel_message_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='OneXtel Message ID')),
                ('failure_reason', models.TextField(blank=True, default='', verbose_name='Failure Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted to Carrier At')),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rcs_messages', to='wallet.senderprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='templates_mgmt.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcs_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RCS Message',
                'verbose_name_plural': 'RCS Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='messaging_m_user_id_d77318_idx'), models.Index(fields=['status'], name='messaging_m_status_7d189b_idx'), models.Index(fields=['onextel_message_id'], name='messaging_m_onextel_40bbdf_idx')],
            },
        ),
    ]
