# Generated by Django 5.1.15 on 2026-10-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered At'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_refunded',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Refunded'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read At'),
        ),
        migrations.CreateModel(
            name='DLRLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict, verbose_name='Raw Webhook Payload')),
                ('onextel_message_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='OneXtel Message ID')),
                ('status_extracted', models.CharField(blank=True, max_length=50, verbose_name='Extracted Status')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Processed')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Processing Error')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlr_logs', to='messaging.message')),
            ],
            options={
                'verbose_name': 'DLR Webhook Log',
                'verbose_name_plural': 'DLR Webhook Logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
