# Generated by Django 5.1.15 on 2026-10-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '__first__'),
        ('messaging', '0002_message_delivered_at_message_is_refunded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='campaigns.campaign'),
        ),
    ]
