# Generated by Django 5.1.15 on 2026-10-05 11:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(help_text='RCS Bot / Sender ID configured on carrier / vendor platform', max_length=100, verbose_name='Sender / Bot ID')),
                ('sender_profile_name', models.CharField(help_text='Display brand name shown on customer handsets', max_length=255, verbose_name='Sender Profile Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sender Profile',
                'verbose_name_plural': 'Sender Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Wallet Balance (INR)')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('reservation', 'Reservation'), ('release', 'Release')], db_index=True, max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Amount (INR)')),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Balance After (INR)')),
                ('reference_type', models.CharField(blank=True, help_text='E.g. campaign, message, transfer, manual_adjustment', max_length=50, verbose_name='Reference Type')),
                ('reference_id', models.CharField(blank=True, help_text='ID of the associated entity', max_length=100, verbose_name='Reference ID')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('TRANSACTIONAL', 'Transactional'), ('OTP', 'OTP')], max_length=20, verbose_name='Message Type')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Customer selling price per message', max_digits=14, verbose_name='Rate per Message (INR)')),
                ('cost_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Underlying cost rate for margin computation', max_digits=14, verbose_name='Cost Rate (INR)')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate Plan',
                'verbose_name_plural': 'Rate Plans',
                'ordering': ['message_type'],
                'unique_together': {('user', 'message_type')},
            },
        ),
    ]
