# Generated by Django 5.1.15 on 2026-10-05 12:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0002_message_delivered_at_message_is_refunded_and_more'),
        ('templates_mgmt', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Campaign Name')),
                ('message_type', models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('TRANSACTIONAL', 'Transactional'), ('OTP', 'OTP')], default='PROMOTIONAL', max_length=20, verbose_name='Message Type')),
                ('content_type', models.CharField(choices=[('text', 'Plain Text'), ('rich_card', 'Rich Card'), ('carousel', 'Carousel'), ('template', 'Pre-approved Template')], default='template', max_length=20, verbose_name='Content Type')),
                ('custom_content', models.JSONField(blank=True, default=dict, help_text='Custom text or cards if not utilizing pre-approved template', verbose_name='Custom Content Payload')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('parsing', 'Parsing File'), ('parsed', 'File Parsed'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total Rows')),
                ('valid_count', models.PositiveIntegerField(default=0, verbose_name='Valid Contacts')),
                ('invalid_count', models.PositiveIntegerField(default=0, verbose_name='Invalid Contacts')),
                ('duplicate_count', models.PositiveIntegerField(default=0, verbose_name='Duplicate Contacts')),
                ('processed_count', models.PositiveIntegerField(default=0, verbose_name='Processed Contacts')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='Delivered Count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Failed Count')),
                ('rate_applied', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Rate Applied (INR)')),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Estimated Cost (INR)')),
                ('reserved_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Reserved Amount (INR)')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('file', models.FileField(blank=True, null=True, upload_to='campaigns/uploads/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='campaigns/results/')),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='Mapping from CSV/XLSX columns to mobile and template placeholders', verbose_name='Column Mapping')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='wallet.senderprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='templates_mgmt.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=20, verbose_name='Recipient Number')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Contact Params')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='campaigns.campaign')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_contacts', to='messaging.message')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_77ea88_idx'), models.Index(fields=['campaign', 'number'], name='campaigns_c_campaig_d8e0b5_idx')],
            },
        ),
    ]
