# Generated by Django 5.1.15 on 2026-10-07 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted / Pending Review'), ('forwarded_to_operator', 'Forwarded to Operator'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=30)),
                ('bot_message_type', models.CharField(help_text='Comma-separated selected message types: Promotional, Transactional, OTP', max_length=255, verbose_name='Bot Message Type')),
                ('reseller_name', models.CharField(max_length=255, verbose_name='Reseller Name')),
                ('reseller_spoc_name', models.CharField(max_length=255, verbose_name='Reseller SPOC Name')),
                ('reseller_spoc_designation', models.CharField(max_length=255, verbose_name='Reseller SPOC Designation')),
                ('reseller_spoc_email', models.EmailField(max_length=254, verbose_name='Reseller SPOC Email')),
                ('bot_billing_category', models.CharField(choices=[('Non-Conversational', 'Non-Conversational'), ('Conversational', 'Conversational')], default='Non-Conversational', max_length=50, verbose_name='Bot Billing Category')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('bot_name', models.CharField(help_text='At least 1 alpha character. Max of 40 characters.', max_length=40, verbose_name='Bot Name')),
                ('bot_logo', models.FileField(help_text='Multipart file Max length 50 KB, 224 x 224 px. Extensions: JPG, JPEG, PNG', upload_to='onboarding/logos/', verbose_name='Bot Logo')),
                ('banner_image', models.FileField(help_text='File Size Max: 200 KB, Dimensions: 1440 x 448 px. Extensions: JPG, JPEG, PNG', upload_to='onboarding/banners/', verbose_name='Banner Image')),
                ('short_description', models.CharField(help_text='Max of 100 characters', max_length=100, verbose_name='Short Description')),
                ('color_code', models.CharField(default='#2563EB', help_text='Hex color code, e.g. #2563EB', max_length=20, verbose_name='Colour Code')),
                ('primary_phone', models.CharField(help_text='Valid phone number with country code', max_length=30, verbose_name='Primary Phone Number')),
                ('primary_phone_label', models.CharField(default='Phone', max_length=25, verbose_name='Label for primary phone number')),
                ('primary_email', models.EmailField(help_text='Valid Email ID', max_length=254, verbose_name='Primary Email ID')),
                ('primary_email_label', models.CharField(default='Email', max_length=25, verbose_name='Label for primary email id')),
                ('primary_website', models.URLField(help_text='Valid website URL', verbose_name='Primary Website')),
                ('primary_website_label', models.CharField(default='Website', max_length=25, verbose_name='Label for primary website')),
                ('terms_conditions_url', models.URLField(max_length=2048, verbose_name='Terms and Conditions URL')),
                ('privacy_url', models.URLField(max_length=2048, verbose_name='Privacy URL')),
                ('languages_supported', models.CharField(default='English', help_text='Ex: English, Hindi', max_length=255, verbose_name='Languages Supported')),
                ('opt_in_screenshot', models.FileField(help_text='Screenshot showcasing how opt-in is collected from customers for carrier verification.', upload_to='onboarding/opt_in/', verbose_name='Opt-in Screenshot')),
                ('operator_name', models.CharField(blank=True, default='Vodafone / VI', max_length=100, verbose_name='Operator / Carrier')),
                ('operator_reference_id', models.CharField(blank=True, max_length=100, verbose_name='Operator Reference ID')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes / Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The client/user who submitted this application', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Application',
                'verbose_name_plural': 'Onboarding Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
