# Generated by Django 5.1.15 on 2026-10-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingapplication',
            name='brand_spoc_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Brand SPOC Designation'),
        ),
        migrations.AddField(
            model_name='onboardingapplication',
            name='brand_spoc_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Brand SPOC Email'),
        ),
        migrations.AddField(
            model_name='onboardingapplication',
            name='brand_spoc_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Brand SPOC Name'),
        ),
        migrations.AddField(
            model_name='onboardingapplication',
            name='gst_certificate',
            field=models.FileField(blank=True, help_text='Upload 1 supported file: PDF. Max 10 MB.', null=True, upload_to='onboarding/gst/', verbose_name='GST Certificate'),
        ),
        migrations.AddField(
            model_name='onboardingapplication',
            name='pan_card',
            field=models.FileField(blank=True, help_text='Upload 1 supported file. Max 10 MB.', null=True, upload_to='onboarding/pan/', verbose_name='PAN Card'),
        ),
    ]
