# Generated by Django 5.1.15 on 2026-10-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingapplication_brand_spoc_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingapplication',
            name='reseller_name',
        ),
        migrations.RemoveField(
            model_name='onboardingapplication',
            name='reseller_spoc_designation',
        ),
        migrations.RemoveField(
            model_name='onboardingapplication',
            name='reseller_spoc_email',
        ),
        migrations.RemoveField(
            model_name='onboardingapplication',
            name='reseller_spoc_name',
        ),
    ]
