# Generated by Django 5.1.15 on 2026-10-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_remove_onboardingapplication_reseller_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingapplication',
            name='bot_billing_category',
        ),
    ]
