# Generated by Django 5.1.15 on 2026-10-05 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rcs_media/%Y/%m/%d/')),
                ('public_url', models.URLField(blank=True, max_length=1000, verbose_name='Public URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name containing letters, digits, and underscores only.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Template name must be alphanumeric and underscores only, with no spaces.', regex='^[a-zA-Z0-9_]+$')], verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('text_message', 'Text Message'), ('text_message_with_media', 'Text with Media'), ('rich_card', 'Rich Card (Standalone)'), ('carousel', 'Carousel')], db_index=True, max_length=30, verbose_name='Template Type')),
                ('message_type', models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('TRANSACTIONAL', 'Transactional'), ('OTP', 'OTP')], db_index=True, max_length=20, verbose_name='Message Type')),
                ('payload', models.JSONField(default=dict, help_text='Structured JSON conforming to OneXtel specification.', verbose_name='Template Payload')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Approval Status')),
                ('onextel_status_raw', models.CharField(blank=True, max_length=100, verbose_name='OneXtel Raw Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcs_templates', to=settings.AUTH_USER_MODEL)),
                ('sender_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='wallet.senderprofile')),
            ],
            options={
                'verbose_name': 'RCS Template',
                'verbose_name_plural': 'RCS Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
